name: Test Suite

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test_harness:
    env:
      TEST_DIR: test_harness
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
      RUNNER_CMD: pub run test -r expanded
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_args: [-t cli, -x cli]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ${{ env.RUNNER_CMD }}

  conduit:
    env:
      TEST_DIR: conduit
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
      RUNNER_CMD: pub run test -r expanded
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        runner_args: [-t cli, -x cli]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ${{ env.RUNNER_CMD }} ${{ matrix.runner_args }}

  conduit_tool:
    env:
      TEST_DIR: ci
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Get Conduit Dependencies
        working-directory: conduit
        run: dart pub get
      - name: Global Activate
        run: |
          dart pub global activate --source path codable
          dart pub global activate --source path common
          dart pub global activate --source path config
          dart pub global activate --source path isolate_exec
          dart pub global activate --source path open_api
          dart pub global activate --source path password_hash
          dart pub global activate --source path test_harness
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ls $PUB_CACHE/* && export PATH=$PATH:$PUB_CACHE/bin:$PUB_CACHE && dart generated_test_runner.dart
